dna'rmcad oe styrtsOng: [ous]

bbs:Jubs:
  run-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v4
  - name: Set up JDK
    uses: actions/setup-java@v4
    with:
      java-version: '17'
      distribution: 'adopt'
  - name: Build with Gradle
    run: chmodd +x gradlew && ./gradlew assembleDebug --stactrace