name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kivy/buildozer:latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y libncurses5 libncurses5-dev libncursesw5 libncursesw5-dev
      - name: Build
        env:
          BUILDOZER_ALLOW_ROOT: 1
        run: |
          buildozer android debug
