name: Build APK
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-setuptools autoconf automake libtool
          pip3 install --upgrade buildozer cython
      - name: Build APK
        run: |
          export BUILDOZER_ALLOW_ROOT=1
          mkdir -p ~/.buildozer/android/platform/android-sdk/licenses
          echo "24333f15532b47ef2ea9845eab0d94765db16e1c" > ~/.buildozer/android/platform/android-sdk/licenses/android-sdk-license
          echo "84831b9409646a918e30573bab4c9c91346d8abd" >> ~/.buildozer/android/platform/android-sdk/licenses/android-sdk-license
          echo "d8aa0f1305ad0a244a1aaf103d7aa4604ea9fd18" >> ~/.buildozer/android/platform/android-sdk/licenses/android-googletv-license
          echo "601085b94cd77f0b54ff86406957099ebe79c4d" >> ~/.buildozer/android/platform/android-sdk/licenses/android-sdk-preview-license
          buildozer android debug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: bin/*.apk
