name: Rust Android Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: rustup target add aarch64-linux-android
      - name: Build
        run: cargo build --target aarch64-linux-android --release
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: librust_core
          path: target/aarch64-linux-android/release/librust_core.so
