name: Rust Android Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Show directory structure
        run: ls -R  # ЭТО ПОКАЖЕТ НАМ ВСЕ ФАЙЛЫ В ЛОГАХ
        
      - name: Install Rust
        run: rustup target add aarch64-linux-android
        
      - name: Build
        run: cargo build --release --target aarch64-linux-android --manifest-path rust_core/Cargo.toml
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: librust_core
          path: rust_core/target/aarch64-linux-android/release/librust_core.so
